params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: normc_initializer
          std: 0.01
        sigma_init:
          name: const_initializer
          value: 0
        fixed_sigma: True

    cnn:
      type: conv1d
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 128
          kernel_size: 2
          strides: 1
          padding: 'valid'

    mlp:
      units: [256, 128]
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001
    #lstm:
    #  units: 128
    #  concated: False
  load_checkpoint: False
  load_path: 'nn/walker_0_0ep=813.0rew=287.86985430901296'

  config:
      reward_shaper:
        scale_value: 0.1
        min_val: -1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.9
      learning_rate: 1e-4
      name: walker
      score_to_win: 300
      grad_norm: 0.5
      entropy_coef: 0.000
      truncate_grads: True
      env_name:  BipedalWalkerHardcoreCnn-v2
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 16
      steps_num: 256
      minibatch_size: 2048
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  adaptive
      lr_threshold: 0.008
      normalize_input: False
      seq_len: 8
      bounds_loss_coef: 0.5
      max_epochs: 20000

experiment_config:
  start_exp: 0
  start_sub_exp: 0
  experiments:
    - exp:
      - path: network.separate
        value: [False, True]