params:  
  algo:
    name: dqn

  model:
    name: dqn

  load_checkpoint: False
  load_path: path

  network:
    name: dqn
    space: 
      discrete:

    dueling: True
    atoms: 1
    noisy: False
    cnn:
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2

      convs:    
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 'same'
        - filters: 32
          kernel_size: 3
          strides: 1
          padding: 'same'

    mlp:
      units: [256]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2

  config:
    reward_scale: 1
    reward_shift: 0
    gamma : 0.99
    learning_rate : 0.0001
    steps_per_epoch : 4
    batch_size : 128
    epsilon : 0.99
    min_epsilon : 0.02
    epsilon_decay_frames : 100000
    num_epochs_to_copy : 10000
    name : 'connectx'
    env_name:  connectx
    is_double : True
    score_to_win : 100
    num_steps_fill_buffer : 10000
    replay_buffer_type : 'normal'
    replay_buffer_size : 100000
    priority_beta : 0.4
    priority_alpha : 0.6
    beta_decay_frames : 100000
    max_beta : 1
    steps_num : 3
    episodes_to_log : 10
    lives_reward : 1
    atoms_num : 1
    games_to_track : 1000
    lr_schedule : None
    max_epochs: 1000000
    self_play:
      score_to_update: 0.2