params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: path

  network:
    name: actor_critic
    separate: True
    space: 
      discrete:

    mlp:
      units: [512,256,128]
      activation: relu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237

  config:
    reward_scale: 1
    reward_shift: 0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.9
    learning_rate: 1e-4
    name: connectx_ppo
    score_to_win: 20.9
    grad_norm: 0.5
    entropy_coef: 0.008
    truncate_grads: True
    env_name:  connectx
    ppo: true
    e_clip: 0.2
    clip_value: true
    num_actors: 32
    steps_num: 16
    minibatch_size: 128
    mini_epochs: 8
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.008
    normalize_input: False
    seq_len: 8