algo:
  name: a2c_continuous

model:
  name: continuous_a2c_logstd

 
network:
  name: actor_critic_continuous
  separate: true
  fixed_sigma: true
  sizes: [256, 128, 64]
  activations: [relu, relu, relu]
  mu_activation: none
  sigma_activation: none

load_checkpoint: false
load_path: path

config:
    REWARD_SCALE: 0.1
    REWARD_SHIFT: 0
    NORMALIZE_ADVANTAGE: True
    GAMMA: 0.99
    TAU: 0.9
    LEARNING_RATE: 1e-4
    NAME: robo1
    SCORE_TO_WIN: 300
    GRAD_NORM: 0.5
    ENTROPY_COEF: 0.000
    TRUNCATE_GRADS: True
    ENV_NAME:  BipedalWalkerHardcore-v2
    PPO: true
    E_CLIP: 0.2
    CLIP_VALUE: True
    NUM_ACTORS: 16
    STEPS_NUM: 256
    MINIBATCH_SIZE: 1024
    MINI_EPOCHS: 8
    CRITIC_COEF: 1
    LR_SCHEDULE:  NONE
    LR_THRESHOLD: 0.008
    NORMALIZE_INPUT: False
    SEQ_LEN: 8
