params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/sc2smac'

  network:
    name: actor_critic
    separate: True
    space: 
      discrete:
      
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
      regularizer:
        name: 'None'
  config:
    reward_shaper:
        scale_value: 0.1
    normalize_advantage: True
    gamma: 0.995
    tau: 0.9
    learning_rate: 1e-4
    name: sc2_3m_fc
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.002
    truncate_grads: True
    env_name:  smac
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 256
    mini_epochs: 8
    critic_coef: 1
    lr_schedule:  Adaptive
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 4
    use_action_masks: True