params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: True
  load_path: 'nn/sc2smac_cnn'

  network:
    name: actor_critic
    separate: True
    normalization: layer_norm
    space: 
      discrete:
      
    cnn:
      type: conv1d
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      convs:    
        - filters: 64
          kernel_size: 3
          strides: 2
          padding: 'same'
        - filters: 128
          kernel_size: 3
          strides: 1
          padding: 'valid'
        - filters: 256
          kernel_size: 3
          strides: 1
          padding: 'valid'

    mlp:
      units: [256, 128]
      activation: elu
      initializer:
        name: variance_scaling_initializer
        scale: 2 
      regularizer:
        name:  'None'
  config:
    reward_shaper:
        scale_value: 0.1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.9
    learning_rate: 1e-8
    name: sc2
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.02
    truncate_grads: True
    env_name:  smac_cnn
    ppo: true
    e_clip: 0.1
    clip_value: True
    num_actors: 8
    steps_num: 128
    minibatch_size: 256
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.2
    normalize_input: False
    seq_len: 4
    use_action_masks: True