params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 'nn/sc2smac'

  network:
    name: actor_critic
    separate: True
    space: 
      discrete:
      
    mlp:
      units: [512, 256, 128]
      activation: elu
      initializer:
        name: orthogonal_initializer
        gain: 1.41421356237
      regularizer:
        name: 'None'
  config:
    name: sc2_fc
    reward_shaper:
        scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    score_to_win: 1000
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name:  smac
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 8
    steps_num: 64
    minibatch_size: 1536
    mini_epochs: 8
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.05
    normalize_input: False
    seq_len: 4
    use_action_masks: True

    env_config:
      name: 6h_vs_8z
      frames: 4
      #transpose: True
      random_invalid_step: False