params:  
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: normc_initializer
          std: 0.01
        sigma_init:
          name: const_initializer
          value: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 128]
      activation: elu
      initializer:
        name: normc_initializer
        std: 1        
      regularizer:
        name:  'None' #'l2_regularizer'
        #scale: 0.001

  load_checkpoint: False
  load_path: path

  config:
      reward_scale: 0.1
      reward_shift: 0
      normalize_advantage: True
      gamma: 0.99
      tau: 0.9
      learning_rate: 1e-4
      name: walker
      score_to_win: 280
      grad_norm: 0.5
      entropy_coef: 0.000
      truncate_grads: True
      env_name:  BipedalWalkerHardcore-v2
      ppo: true
      e_clip: 0.2
      clip_value: True
      num_actors: 16
      steps_num: 256
      minibatch_size: 1024
      mini_epochs: 8
      critic_coef: 1
      lr_schedule:  adaptive
      lr_threshold: 0.002
      normalize_input: False
      seq_len: 8
      bounds_loss_coef: 1


experiment_config:
  start_exp: 0
  start_sub_exp: 0
  experiments:
    - exp:
      - path: config.bounds_loss_coef
        value: [1, 0.5, 0]