params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  load_checkpoint: False
  load_path: 

  network:
    name: resnet_actor_critic
    separate: False
    value_shape: 1
    space: 
      discrete:
    
    cnn:
      conv_depths: [16, 32, 32]
      activation: relu
      initializer:
        name: variance_scaling_initializer
        scale: 2
      regularizer:
        name: 'None'
      
    mlp:
      units: [512]
      activation: relu
      regularizer:
        name: 'None'
      initializer:
        name: variance_scaling_initializer
        scale: 2 
    rnn1:
      name: lstm
      units: 256
      layers: 1
  config:
    reward_shaper:
        scale_value: 0.1
        
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    name: atari
    score_to_win: 900
    grad_norm: 0.5
    entropy_coef: 0.005
    truncate_grads: True
    env_name: 'BreakoutNoFrameskip-v4' #'openai_gym' #'PongNoFrameskip-v4' #
    ppo: true
    e_clip: 0.2
    clip_value: True
    num_actors: 16
    steps_num: 128
    minibatch_size: 1024
    mini_epochs: 4
    critic_coef: 1
    lr_schedule:  None
    lr_threshold: 0.008
    normalize_input: False
    seq_len: 4
    max_epochs: 5000
    env_config1:
        name: "procgen:procgen-coinrun-v0"
        procgen: True
        frames: 1
        num_levels: 10
        start_level: 322